server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: local
    enabled: true

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  file:
    name: ./logs/monitoringService.log
