--liquibase formatted sql

--changeset deekul:create_table_measurements

create table measurements
(
    id bigint generated by default as identity primary key,
    value double precision not null,
    raining boolean not null,
    measurement_date_time timestamp not null,
    sensor varchar(255) references sensors(name)
);