--liquibase formatted sql

--changeset deekul:20240911_create_table_measurements

CREATE TABLE measurements
(
    id bigint generated by default as identity primary key,
    value double precision not null,
    raining boolean not null,
    measurement_date_time timestamp not null,
    sensor varchar(255) references sensors(name)
);