--liquibase formatted sql

--changeset deekul:20241011_create_table_sensors

create table sensors
(
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique
);